#
# Makefile for the linux m68k-specific parts of the memory manager.
#

obj-y	 := init.o fault.o memory.o kmap.o
# Makefile for the linux h8300-specific parts of the memory manager.
#

obj-y	 := init.o fault.o memory.o
