#
# Makefile for the BCM47XX specific kernel interface routines
# under Linux.
#

obj-y := gpio.o irq.o prom.o serial.o setup.o time.o wgt634u.o
obj-y				+= irq.o prom.o serial.o setup.o time.o sprom.o
obj-y				+= irq.o prom.o serial.o setup.o time.o
obj-y				+= board.o buttons.o leds.o workarounds.o
