obj-m := DocBook/ accounting/ auxdisplay/ connector/ \
	filesystems/configfs/ ia64/ networking/ \
	pcmcia/ spi/ video4linux/ vm/ watchdog/src/
subdir-y := accounting auxdisplay blackfin connector \
	filesystems filesystems ia64 laptops misc-devices \
	pcmcia prctl ptp spi timers vDSO video4linux watchdog
